#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

if bspc query -M -m eDP-1 >/dev/null 2>&1; then
	bspc monitor eDP-1 -d I II III IV
fi

if bspc query -M -m HDMI-1-0 >/dev/null 2>&1; then
	bspc monitor HDMI-1-0 -d V VI VII VIII IX X
fi

if [ "$(bspc query -D | wc -l)" -eq 0 ]; then
	bspc monitor -d I II III IV V VI VII VIII IX X
fi

bspc config border_width        1
bspc config window_gap          4
bspc config split_ratio          0.5
#bspc config borderless_monocle   true
#bspc config gapless_monocle      true

#bspc config normal_border_color "#FFFFFF"
#bspc config focused_border_color "#1F8999"
#bspc config urgent_border_color "#B58900"
#bspc config presel_border_color "#26E2FF"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#bspc config window_gap                6
#bspc config split_ratio               0.51
#bspc config single_monocle            true
#bspc config borderless_monocle        false
#bspc config gapless_monocle           false

#
# polybar, autostart, wallpaper, etc. go here when those modules are added
#
